services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: my_password_lol
      POSTGRES_DB: test-demetra
    ports:
      - '5433:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - '6379:6379'
    restart: always

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: server_container
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    restart: always

volumes:
  db_data:
